CREATE OR REPLACE VIEW V_CHEEPS
(
    CHEEP_ID
  , USER_ID
  , CHEEPED_TEXT
  , CHEEPED_APPLICATION_NAME
  , PARENT_CHEEP_ID
  , LIKES_NUMBER
  , DISLIKES_NUMBER
  , RECHEEPS_NUMBER
  , IS_DELETED
  , CREATED_AT
  , UPDATED_AT
) AS SELECT
    CHE.CHEEP_ID
  , CHE.USER_ID
  , CHE.CHEEPED_TEXT
  , CHE.CHEEPED_APPLICATION_NAME
  , CHE.PARENT_CHEEP_ID
  , CASE WHEN AGG_EVA.LIKES_NUMBER IS NOT NULL
    THEN AGG_EVA.LIKES_NUMBER
    ELSE 0
    END
  , CASE WHEN AGG_EVA.DISLIKES_NUMBER IS NOT NULL
    THEN AGG_EVA.DISLIKES_NUMBER
    ELSE 0
    END
  , CASE WHEN AGG_RCH.RECHEEPS_NUMBER IS NOT NULL
    THEN AGG_RCH.RECHEEPS_NUMBER
    ELSE 0
    END
  , CHE.IS_DELETED
  , CHE.CREATED_AT
  , CHE.UPDATED_AT
FROM T_CHEEPS CHE
   , (
        SELECT
            EVA.CHEEP_ID
          , SUM(
                CASE WHEN EVA.EVALUATION_STATUS = '0'
                THEN 1
                ELSE 0
                END
            ) LIKES_NUMBER
          , SUM(
                CASE WHEN EVA.EVALUATION_STATUS = '1'
                THEN 1
                ELSE 0
                END
            ) DISLIKES_NUMBER
        FROM T_CHEEP_EVALUATIONS EVA
        WHERE EVA.IS_DELETED = '0'
        GROUP BY EVA.CHEEP_ID
     ) AGG_EVA
   , (
        SELECT
            RCH.CHEEP_ID
          , COUNT(RCH.USER_ID) RECHEEPS_NUMBER
        FROM T_CHEEP_RECHEEPS RCH
        WHERE RCH.IS_DELETED = '0'
        GROUP BY RCH.CHEEP_ID
     ) AGG_RCH
WHERE CHE.CHEEP_ID = AGG_EVA.CHEEP_ID (+)
  AND CHE.CHEEP_ID = AGG_RCH.CHEEP_ID (+)
;
COMMENT ON TABLE V_CHEEPS IS 'チープビュー';
COMMENT ON COLUMN V_CHEEPS.CHEEP_ID IS 'チープID';
COMMENT ON COLUMN V_CHEEPS.USER_ID IS 'ユーザID';
COMMENT ON COLUMN V_CHEEPS.CHEEPED_TEXT IS 'チープ本文';
COMMENT ON COLUMN V_CHEEPS.CHEEPED_APPLICATION_NAME IS 'チープアプリ名';
COMMENT ON COLUMN V_CHEEPS.PARENT_CHEEP_ID IS '親チープID';
COMMENT ON COLUMN V_CHEEPS.LIKES_NUMBER IS 'いいね数';
COMMENT ON COLUMN V_CHEEPS.DISLIKES_NUMBER IS 'よくないね数';
COMMENT ON COLUMN V_CHEEPS.RECHEEPS_NUMBER IS 'リチープ数';
COMMENT ON COLUMN V_CHEEPS.IS_DELETED IS '削除フラグ';
COMMENT ON COLUMN V_CHEEPS.CREATED_AT IS 'チープ日時';
COMMENT ON COLUMN V_CHEEPS.UPDATED_AT IS '更新日時';
